# Generated by Django 4.1 on 2022-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_scoops_order_flavors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pickup_time']},
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
